services:
  web:
    image: ${IMAGE}
    ports:
      - 80:8080
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_URL: ${DB_URL}
      ENV: ${ENV}