name: deploy

on:
  workflow_dispatch:

env:
  REPOSITORY: vxdiazdel/images
  IMAGE_TAG: wtfemojis_api_${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Copy files to DigitalOcean
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_PRIVATE_KEY }}
          passphrase: ${{ secrets.DO_PASSPHRASE }}
          source: docker-compose.prod.yml,deploy.sh
          target: /home/deploy/app

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.2.0
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_URL: ${{ secrets.DB_URL }}
          IMAGE: ${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          ENV: production
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_PRIVATE_KEY }}
          passphrase: ${{ secrets.DO_PASSPHRASE }}
          envs: DOCKERHUB_USER,DOCKERHUB_TOKEN,DB_HOST,DB_PORT,DB_USER,DB_PASSWORD,DB_NAME,DB_URL,IMAGE,ENV
          script: |
            cd /home/deploy/app
            ./deploy.sh